import type { AiApiFormat } from '../shared/api-types'

export interface UniversalProviderPreset {
  name: string
  providerType: string
  defaultModel: string
  defaultBaseUrl?: string
  websiteUrl?: string
  apiKeyUrl?: string
  apiFormat: AiApiFormat
  modelsUrl?: string
  icon?: string
  iconColor?: string
  endpointCandidates?: string[]
  description?: string
  category?: string
  isOfficial?: boolean
  isPartner?: boolean
  primePartner?: boolean
  isCustomTemplate?: boolean
}

const PRESETS: UniversalProviderPreset[] = [
  {
    name: '自定义配置',
    providerType: 'custom',
    defaultModel: 'gpt-5.5',
    defaultBaseUrl: '',
    apiFormat: 'openai_responses',
    icon: 'custom',
    iconColor: '#64748B',
    description: '手动填写请求地址、模型、API Key，系统按 API 格式自动适配。',
    category: 'custom',
    isCustomTemplate: true,
  },
  {
    name: 'OpenAI Official',
    providerType: 'openai_official',
    defaultModel: 'gpt-5.5',
    defaultBaseUrl: 'https://api.openai.com/v1',
    websiteUrl: 'https://chatgpt.com/codex',
    apiKeyUrl: 'https://platform.openai.com/api-keys',
    apiFormat: 'openai_responses',
    icon: 'openai',
    iconColor: '#00A67E',
    category: 'official',
    isOfficial: true,
  },
  {
    name: 'Kimi',
    providerType: 'kimi',
    defaultModel: 'kimi-k2.7-code',
    defaultBaseUrl: 'https://api.moonshot.cn/v1',
    websiteUrl: 'https://platform.kimi.com?aff=cc-switch',
    apiKeyUrl: 'https://platform.kimi.com/console/api-keys?aff=cc-switch',
    apiFormat: 'openai_chat',
    icon: 'kimi',
    iconColor: '#6366F1',
    endpointCandidates: ['https://api.moonshot.cn/v1'],
    category: 'cn_official',
    primePartner: true,
  },
  {
    name: 'Kimi For Coding',
    providerType: 'kimi_for_coding',
    defaultModel: 'kimi-for-coding',
    defaultBaseUrl: 'https://api.kimi.com/coding/v1',
    websiteUrl: 'https://www.kimi.com/code/?aff=cc-switch',
    apiKeyUrl: 'https://www.kimi.com/code/?aff=cc-switch',
    apiFormat: 'openai_chat',
    icon: 'kimi',
    iconColor: '#6366F1',
    endpointCandidates: ['https://api.kimi.com/coding/v1'],
    category: 'cn_official',
    primePartner: true,
  },
  {
    name: '胜算云',
    providerType: 'shengsuanyun',
    defaultModel: 'openai/gpt-5.5',
    defaultBaseUrl: 'https://router.shengsuanyun.com/api/v1',
    websiteUrl: 'https://www.shengsuanyun.com/?from=CH_4HHXMRYF',
    apiKeyUrl: 'https://www.shengsuanyun.com/?from=CH_4HHXMRYF',
    apiFormat: 'openai_responses',
    icon: 'shengsuanyun',
    category: 'aggregator',
    isPartner: true,
  },
  {
    name: 'PatewayAI',
    providerType: 'patewayai',
    defaultModel: 'gpt-5.5',
    defaultBaseUrl: 'https://api.pateway.ai/v1',
    websiteUrl: 'https://pateway.ai',
    apiKeyUrl: 'https://pateway.ai/?ch=etzpm8&aff=WB6M6F67#/',
    apiFormat: 'openai_responses',
    icon: 'pateway',
    endpointCandidates: ['https://api.pateway.ai/v1'],
    category: 'third_party',
    isPartner: true,
  },
  {
    name: '火山Agentplan',
    providerType: 'agentplan',
    defaultModel: 'ark-code-latest',
    defaultBaseUrl: 'https://ark.cn-beijing.volces.com/api/coding/v3',
    websiteUrl: 'https://www.volcengine.com/product/ark',
    apiKeyUrl: 'https://www.volcengine.com/activity/codingplan?ac=MMAP8JTTCAQ2&rc=6J6FV5N2&utm_campaign=hw&utm_content=ccswitch&utm_medium=devrel_tool_web&utm_source=OWO&utm_term=ccswitch',
    apiFormat: 'openai_chat',
    icon: 'huoshan',
    iconColor: '#3370FF',
    endpointCandidates: ['https://ark.cn-beijing.volces.com/api/coding/v3'],
    category: 'cn_official',
    isPartner: true,
  },
  {
    name: 'BytePlus',
    providerType: 'byteplus',
    defaultModel: 'ark-code-latest',
    defaultBaseUrl: 'https://ark.ap-southeast.bytepluses.com/api/coding/v3',
    websiteUrl: 'https://www.byteplus.com/en/product/modelark',
    apiKeyUrl: 'https://www.byteplus.com/en/product/modelark?utm_campaign=hw&utm_content=ccswitch&utm_medium=devrel_tool_web&utm_source=OWO&utm_term=ccswitch',
    apiFormat: 'openai_chat',
    icon: 'byteplus',
    iconColor: '#3370FF',
    endpointCandidates: ['https://ark.ap-southeast.bytepluses.com/api/coding/v3'],
    category: 'cn_official',
    isPartner: true,
  },
  {
    name: 'DouBaoSeed',
    providerType: 'doubaoseed',
    defaultModel: 'doubao-seed-2-1-pro-260628',
    defaultBaseUrl: 'https://ark.cn-beijing.volces.com/api/v3',
    websiteUrl: 'https://www.volcengine.com/product/doubao',
    apiKeyUrl: 'https://console.volcengine.com/ark/region:ark+cn-beijing/apiKey?apikey=%7B%7D&utm_campaign=hw&utm_content=ccswitch&utm_medium=devrel_tool_web&utm_source=OWO&utm_term=ccswitch',
    apiFormat: 'openai_responses',
    icon: 'doubao',
    iconColor: '#3370FF',
    endpointCandidates: ['https://ark.cn-beijing.volces.com/api/v3'],
    category: 'cn_official',
    isPartner: true,
  },
  {
    name: 'CCSub',
    providerType: 'ccsub',
    defaultModel: 'gpt-5.5',
    defaultBaseUrl: 'https://www.ccsub.net/v1',
    websiteUrl: 'https://www.ccsub.net',
    apiKeyUrl: 'https://www.ccsub.net/register?ref=Y6Z8DXEA',
    apiFormat: 'openai_responses',
    icon: 'ccsub',
    endpointCandidates: ['https://www.ccsub.net/v1'],
    category: 'aggregator',
    isPartner: true,
  },
  {
    name: 'SubRouter',
    providerType: 'subrouter',
    defaultModel: 'gpt-5.5',
    defaultBaseUrl: 'https://subrouter.ai/v1',
    websiteUrl: 'https://subrouter.ai',
    apiKeyUrl: 'https://subrouter.ai/register?aff=l3ri',
    apiFormat: 'openai_responses',
    icon: 'subrouter',
    endpointCandidates: ['https://subrouter.ai/v1'],
    category: 'aggregator',
    isPartner: true,
  },
  {
    name: 'Unity2.ai',
    providerType: 'unity2_ai',
    defaultModel: 'gpt-5.5',
    defaultBaseUrl: 'https://api.unity2.ai',
    websiteUrl: 'https://unity2.ai',
    apiKeyUrl: 'https://unity2.ai/register?source=ccs',
    apiFormat: 'openai_responses',
    icon: 'unity2',
    endpointCandidates: ['https://api.unity2.ai'],
    category: 'aggregator',
    isPartner: true,
  },
  {
    name: 'Azure OpenAI',
    providerType: 'azure_openai',
    defaultModel: 'gpt-5.5',
    defaultBaseUrl: 'https://YOUR_RESOURCE_NAME.openai.azure.com/openai',
    websiteUrl: 'https://learn.microsoft.com/en-us/azure/ai-foundry/openai/how-to/codex',
    apiFormat: 'openai_responses',
    icon: 'azure',
    iconColor: '#0078D4',
    endpointCandidates: ['https://YOUR_RESOURCE_NAME.openai.azure.com/openai'],
    category: 'third_party',
    isOfficial: true,
  },
  {
    name: 'DeepSeek',
    providerType: 'deepseek',
    defaultModel: 'deepseek-v4-flash',
    defaultBaseUrl: 'https://api.deepseek.com',
    websiteUrl: 'https://platform.deepseek.com',
    apiKeyUrl: 'https://platform.deepseek.com/api_keys',
    apiFormat: 'openai_chat',
    modelsUrl: 'https://api.deepseek.com/models',
    icon: 'deepseek',
    iconColor: '#1E88E5',
    endpointCandidates: ['https://api.deepseek.com'],
    category: 'cn_official',
  },
  {
    name: 'Zhipu GLM',
    providerType: 'zhipu_glm',
    defaultModel: 'glm-5.2',
    defaultBaseUrl: 'https://open.bigmodel.cn/api/coding/paas/v4',
    websiteUrl: 'https://open.bigmodel.cn',
    apiKeyUrl: 'https://www.bigmodel.cn/claude-code?ic=RRVJPB5SII',
    apiFormat: 'openai_chat',
    icon: 'zhipu',
    iconColor: '#0F62FE',
    endpointCandidates: ['https://open.bigmodel.cn/api/coding/paas/v4'],
    category: 'cn_official',
  },
  {
    name: 'Zhipu GLM en',
    providerType: 'zhipu_glm_en',
    defaultModel: 'glm-5.2',
    defaultBaseUrl: 'https://api.z.ai/api/coding/paas/v4',
    websiteUrl: 'https://z.ai',
    apiKeyUrl: 'https://z.ai/subscribe?ic=8JVLJQFSKB',
    apiFormat: 'openai_chat',
    icon: 'zhipu',
    iconColor: '#0F62FE',
    endpointCandidates: ['https://api.z.ai/api/coding/paas/v4'],
    category: 'cn_official',
  },
  {
    name: 'Baidu Qianfan Coding Plan',
    providerType: 'baidu_qianfan_coding_plan',
    defaultModel: 'qianfan-code-latest',
    defaultBaseUrl: 'https://qianfan.baidubce.com/v2/coding',
    websiteUrl: 'https://cloud.baidu.com/product/qianfan_modelbuilder',
    apiKeyUrl: 'https://console.bce.baidu.com/qianfan/ais/console/applicationConsole/application',
    apiFormat: 'openai_chat',
    icon: 'baidu',
    iconColor: '#2932E1',
    endpointCandidates: ['https://qianfan.baidubce.com/v2/coding'],
    category: 'cn_official',
  },
  {
    name: 'Bailian',
    providerType: 'bailian',
    defaultModel: 'qwen3-coder-plus',
    defaultBaseUrl: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
    websiteUrl: 'https://bailian.console.aliyun.com',
    apiKeyUrl: 'https://bailian.console.aliyun.com/#/api-key',
    apiFormat: 'openai_responses',
    icon: 'bailian',
    iconColor: '#624AFF',
    endpointCandidates: ['https://dashscope.aliyuncs.com/compatible-mode/v1'],
    category: 'cn_official',
  },
  {
    name: 'StepFun',
    providerType: 'stepfun',
    defaultModel: 'step-3.7-flash',
    defaultBaseUrl: 'https://api.stepfun.com/step_plan/v1',
    websiteUrl: 'https://platform.stepfun.com/step-plan',
    apiKeyUrl: 'https://platform.stepfun.com/interface-key',
    apiFormat: 'openai_chat',
    icon: 'stepfun',
    iconColor: '#16D6D2',
    endpointCandidates: ['https://api.stepfun.com/step_plan/v1'],
    category: 'cn_official',
  },
  {
    name: 'StepFun en',
    providerType: 'stepfun_en',
    defaultModel: 'step-3.7-flash',
    defaultBaseUrl: 'https://api.stepfun.ai/step_plan/v1',
    websiteUrl: 'https://platform.stepfun.ai/step-plan',
    apiKeyUrl: 'https://platform.stepfun.ai/interface-key',
    apiFormat: 'openai_chat',
    icon: 'stepfun',
    iconColor: '#16D6D2',
    endpointCandidates: ['https://api.stepfun.ai/step_plan/v1'],
    category: 'cn_official',
  },
  {
    name: 'ModelScope',
    providerType: 'modelscope',
    defaultModel: 'ZhipuAI/GLM-5.1',
    defaultBaseUrl: 'https://api-inference.modelscope.cn/v1',
    websiteUrl: 'https://modelscope.cn',
    apiKeyUrl: 'https://modelscope.cn/my/myaccesstoken',
    apiFormat: 'openai_chat',
    icon: 'modelscope',
    iconColor: '#624AFF',
    endpointCandidates: ['https://api-inference.modelscope.cn/v1'],
    category: 'aggregator',
  },
  {
    name: 'Longcat',
    providerType: 'longcat',
    defaultModel: 'LongCat-2.0-Preview',
    defaultBaseUrl: 'https://api.longcat.chat/openai/v1',
    websiteUrl: 'https://longcat.chat/platform',
    apiKeyUrl: 'https://longcat.chat/platform/api_keys',
    apiFormat: 'openai_responses',
    icon: 'longcat',
    iconColor: '#29E154',
    endpointCandidates: ['https://api.longcat.chat/openai/v1'],
    category: 'cn_official',
  },
  {
    name: 'MiniMax',
    providerType: 'minimax',
    defaultModel: 'MiniMax-M3',
    defaultBaseUrl: 'https://api.minimaxi.com/v1',
    websiteUrl: 'https://platform.minimaxi.com',
    apiKeyUrl: 'https://platform.minimaxi.com/subscribe/coding-plan',
    apiFormat: 'openai_responses',
    icon: 'minimax',
    iconColor: '#FF6B6B',
    endpointCandidates: ['https://api.minimaxi.com/v1'],
    category: 'cn_official',
  },
  {
    name: 'MiniMax en',
    providerType: 'minimax_en',
    defaultModel: 'MiniMax-M3',
    defaultBaseUrl: 'https://api.minimax.io/v1',
    websiteUrl: 'https://platform.minimax.io',
    apiKeyUrl: 'https://platform.minimax.io/subscribe/coding-plan',
    apiFormat: 'openai_responses',
    icon: 'minimax',
    iconColor: '#FF6B6B',
    endpointCandidates: ['https://api.minimax.io/v1'],
    category: 'cn_official',
  },
  {
    name: 'BaiLing',
    providerType: 'bailing',
    defaultModel: 'Ling-2.6-1T',
    defaultBaseUrl: 'https://api.tbox.cn/api/llm/v1',
    websiteUrl: 'https://alipaytbox.yuque.com/sxs0ba/ling/get_started',
    apiKeyUrl: 'https://ling.tbox.cn/open',
    apiFormat: 'openai_chat',
    endpointCandidates: ['https://api.tbox.cn/api/llm/v1'],
    category: 'cn_official',
  },
  {
    name: 'Xiaomi MiMo',
    providerType: 'xiaomi_mimo',
    defaultModel: 'mimo-v2.5-pro',
    defaultBaseUrl: 'https://api.xiaomimimo.com/v1',
    websiteUrl: 'https://platform.xiaomimimo.com',
    apiKeyUrl: 'https://platform.xiaomimimo.com/#/console/api-keys',
    apiFormat: 'openai_responses',
    icon: 'xiaomimimo',
    iconColor: '#000000',
    endpointCandidates: ['https://api.xiaomimimo.com/v1'],
    category: 'cn_official',
  },
  {
    name: 'Xiaomi MiMo Token Plan (China)',
    providerType: 'xiaomi_mimo_token_plan_china',
    defaultModel: 'mimo-v2.5-pro',
    defaultBaseUrl: 'https://token-plan-cn.xiaomimimo.com/v1',
    websiteUrl: 'https://platform.xiaomimimo.com/#/token-plan',
    apiKeyUrl: 'https://platform.xiaomimimo.com/#/console/plan-manage',
    apiFormat: 'openai_responses',
    icon: 'xiaomimimo',
    iconColor: '#000000',
    endpointCandidates: ['https://token-plan-cn.xiaomimimo.com/v1'],
    category: 'cn_official',
  },
  {
    name: 'SiliconFlow',
    providerType: 'siliconflow',
    defaultModel: 'Pro/MiniMaxAI/MiniMax-M2.7',
    defaultBaseUrl: 'https://api.siliconflow.cn/v1',
    websiteUrl: 'https://siliconflow.cn',
    apiKeyUrl: 'https://cloud.siliconflow.cn/i/YflgU2Ve',
    apiFormat: 'openai_chat',
    icon: 'siliconflow',
    iconColor: '#6E29F6',
    endpointCandidates: ['https://api.siliconflow.cn/v1'],
    category: 'aggregator',
    isPartner: true,
  },
  {
    name: 'SiliconFlow en',
    providerType: 'siliconflow_en',
    defaultModel: 'MiniMaxAI/MiniMax-M2.7',
    defaultBaseUrl: 'https://api.siliconflow.com/v1',
    websiteUrl: 'https://siliconflow.com',
    apiKeyUrl: 'https://cloud.siliconflow.cn/i/YflgU2Ve',
    apiFormat: 'openai_chat',
    icon: 'siliconflow',
    iconColor: '#000000',
    endpointCandidates: ['https://api.siliconflow.com/v1'],
    category: 'aggregator',
    isPartner: true,
  },
  {
    name: 'Novita AI',
    providerType: 'novita_ai',
    defaultModel: 'zai-org/glm-5.1',
    defaultBaseUrl: 'https://api.novita.ai/openai/v1',
    websiteUrl: 'https://novita.ai',
    apiKeyUrl: 'https://novita.ai',
    apiFormat: 'openai_chat',
    icon: 'novita',
    iconColor: '#000000',
    endpointCandidates: ['https://api.novita.ai/openai/v1'],
    category: 'aggregator',
  },
  {
    name: 'Nvidia',
    providerType: 'nvidia',
    defaultModel: 'moonshotai/kimi-k2.5',
    defaultBaseUrl: 'https://integrate.api.nvidia.com/v1',
    websiteUrl: 'https://build.nvidia.com',
    apiKeyUrl: 'https://build.nvidia.com/settings/api-keys',
    apiFormat: 'openai_chat',
    icon: 'nvidia',
    iconColor: '#000000',
    endpointCandidates: ['https://integrate.api.nvidia.com/v1'],
    category: 'aggregator',
  },
  {
    name: 'OpenCode Go',
    providerType: 'opencode_go',
    defaultModel: 'glm-5.2',
    defaultBaseUrl: 'https://opencode.ai/zen/go/v1',
    websiteUrl: 'https://opencode.ai/go',
    apiKeyUrl: 'https://opencode.ai/go?ref=2YTRG2NGTX',
    apiFormat: 'openai_chat',
    icon: 'opencode',
    iconColor: '#211E1E',
    endpointCandidates: ['https://opencode.ai/zen/go/v1'],
    category: 'third_party',
  },
  {
    name: 'AiHubMix',
    providerType: 'aihubmix',
    defaultModel: 'gpt-5.5',
    defaultBaseUrl: 'https://aihubmix.com/v1',
    websiteUrl: 'https://aihubmix.com',
    apiFormat: 'openai_responses',
    endpointCandidates: ['https://aihubmix.com/v1', 'https://api.aihubmix.com/v1'],
    category: 'aggregator',
  },
  {
    name: 'CherryIN',
    providerType: 'cherryin',
    defaultModel: 'openai/gpt-5.5',
    defaultBaseUrl: 'https://open.cherryin.net/v1',
    websiteUrl: 'https://open.cherryin.ai',
    apiKeyUrl: 'https://open.cherryin.ai/console/token',
    apiFormat: 'openai_responses',
    icon: 'cherryin',
    endpointCandidates: ['https://open.cherryin.net/v1'],
    category: 'aggregator',
  },
  {
    name: 'DMXAPI',
    providerType: 'dmxapi',
    defaultModel: 'gpt-5.5',
    defaultBaseUrl: 'https://www.dmxapi.cn/v1',
    websiteUrl: 'https://www.dmxapi.cn',
    apiFormat: 'openai_responses',
    endpointCandidates: ['https://www.dmxapi.cn/v1'],
    category: 'aggregator',
    isPartner: true,
  },
  {
    name: 'PackyCode',
    providerType: 'packycode',
    defaultModel: 'gpt-5.5',
    defaultBaseUrl: 'https://www.packyapi.com/v1',
    websiteUrl: 'https://www.packyapi.com',
    apiKeyUrl: 'https://www.packyapi.com/register?aff=cc-switch',
    apiFormat: 'openai_responses',
    icon: 'packycode',
    endpointCandidates: ['https://www.packyapi.com/v1', 'https://api-slb.packyapi.com/v1'],
    category: 'third_party',
    isPartner: true,
  },
  {
    name: 'APIKEY.FUN',
    providerType: 'apikey_fun',
    defaultModel: 'gpt-5.5',
    defaultBaseUrl: 'https://api.apikey.fun/v1',
    websiteUrl: 'https://apikey.fun',
    apiKeyUrl: 'https://apikey.fun/register?aff=CCSwitch',
    apiFormat: 'openai_responses',
    icon: 'apikeyfun',
    endpointCandidates: ['https://api.apikey.fun/v1', 'https://slb.apikey.fun/v1'],
    category: 'third_party',
    isPartner: true,
  },
  {
    name: 'APINebula',
    providerType: 'apinebula',
    defaultModel: 'gpt-5.5',
    defaultBaseUrl: 'https://apinebula.com/v1',
    websiteUrl: 'https://apinebula.com',
    apiKeyUrl: 'https://apinebula.com/02rw5X',
    apiFormat: 'openai_responses',
    icon: 'apinebula',
    endpointCandidates: ['https://apinebula.com/v1'],
    category: 'third_party',
    isPartner: true,
  },
  {
    name: 'AtlasCloud',
    providerType: 'atlascloud',
    defaultModel: 'zai-org/glm-5.1',
    defaultBaseUrl: 'https://api.atlascloud.ai/v1',
    websiteUrl: 'https://www.atlascloud.ai/console/coding-plan',
    apiKeyUrl: 'https://www.atlascloud.ai/console/coding-plan',
    apiFormat: 'openai_chat',
    icon: 'atlascloud',
    endpointCandidates: ['https://api.atlascloud.ai/v1'],
    category: 'aggregator',
    isPartner: true,
  },
  {
    name: 'SudoCode',
    providerType: 'sudocode',
    defaultModel: 'gpt-5.5',
    defaultBaseUrl: 'https://sudocode.us/v1',
    websiteUrl: 'https://sudocode.us',
    apiKeyUrl: 'https://sudocode.us',
    apiFormat: 'openai_responses',
    icon: 'sudocode',
    endpointCandidates: ['https://sudocode.us/v1', 'https://sudocode.run/v1'],
    category: 'third_party',
  },
  {
    name: 'ClaudeCN',
    providerType: 'claudecn',
    defaultModel: 'gpt-5.5',
    defaultBaseUrl: 'https://claudecn.top/v1',
    websiteUrl: 'https://claudecn.top',
    apiKeyUrl: 'https://claudecn.top/register?aff=ccswitch',
    apiFormat: 'openai_responses',
    icon: 'claudecn',
    category: 'third_party',
    isPartner: true,
  },
  {
    name: 'RunAPI',
    providerType: 'runapi',
    defaultModel: 'gpt-5.5',
    defaultBaseUrl: 'https://runapi.co/v1',
    websiteUrl: 'https://runapi.co',
    apiKeyUrl: 'https://runapi.co',
    apiFormat: 'openai_responses',
    icon: 'runapi',
    category: 'aggregator',
    isPartner: true,
  },
  {
    name: 'RelaxyCode',
    providerType: 'relaxycode',
    defaultModel: 'gpt-5.5',
    defaultBaseUrl: 'https://www.relaxycode.com/v1',
    websiteUrl: 'https://www.relaxycode.com',
    apiKeyUrl: 'https://www.relaxycode.com/register',
    apiFormat: 'openai_responses',
    icon: 'relaxcode',
    category: 'third_party',
  },
  {
    name: 'Cubence',
    providerType: 'cubence',
    defaultModel: 'gpt-5.5',
    defaultBaseUrl: 'https://api.cubence.com/v1',
    websiteUrl: 'https://cubence.com',
    apiKeyUrl: 'https://cubence.com/signup?code=CCSWITCH&source=ccs',
    apiFormat: 'openai_responses',
    icon: 'cubence',
    iconColor: '#000000',
    endpointCandidates: [
      'https://api.cubence.com/v1',
      'https://api-cf.cubence.com/v1',
      'https://api-dmit.cubence.com/v1',
      'https://api-bwg.cubence.com/v1',
    ],
    category: 'third_party',
    isPartner: true,
  },
  {
    name: 'AIGoCode',
    providerType: 'aigocode',
    defaultModel: 'gpt-5.5',
    defaultBaseUrl: 'https://api.aigocode.com',
    websiteUrl: 'https://aigocode.com',
    apiKeyUrl: 'https://aigocode.com/invite/CC-SWITCH',
    apiFormat: 'openai_responses',
    icon: 'aigocode',
    iconColor: '#5B7FFF',
    endpointCandidates: ['https://api.aigocode.com'],
    category: 'third_party',
    isPartner: true,
  },
  {
    name: 'RightCode',
    providerType: 'rightcode',
    defaultModel: 'gpt-5.5',
    defaultBaseUrl: 'https://right.codes/codex/v1',
    websiteUrl: 'https://www.right.codes',
    apiKeyUrl: 'https://www.right.codes/register?aff=CCSWITCH',
    apiFormat: 'openai_responses',
    icon: 'rc',
    iconColor: '#E96B2C',
    category: 'third_party',
    isPartner: true,
  },
  {
    name: 'AICodeMirror',
    providerType: 'aicodemirror',
    defaultModel: 'gpt-5.5',
    defaultBaseUrl: 'https://api.aicodemirror.com/api/codex/backend-api/codex',
    websiteUrl: 'https://www.aicodemirror.com',
    apiKeyUrl: 'https://www.aicodemirror.com/register?invitecode=9915W3',
    apiFormat: 'openai_responses',
    icon: 'aicodemirror',
    iconColor: '#000000',
    endpointCandidates: [
      'https://api.aicodemirror.com/api/codex/backend-api/codex',
      'https://api.claudecode.net.cn/api/codex/backend-api/codex',
    ],
    isPartner: true,
  },
  {
    name: 'CrazyRouter',
    providerType: 'crazyrouter',
    defaultModel: 'gpt-5.5',
    defaultBaseUrl: 'https://cn.crazyrouter.com/v1',
    websiteUrl: 'https://www.crazyrouter.com',
    apiKeyUrl: 'https://www.crazyrouter.com/register?aff=OZcm&ref=cc-switch',
    apiFormat: 'openai_responses',
    icon: 'crazyrouter',
    iconColor: '#000000',
    endpointCandidates: ['https://cn.crazyrouter.com/v1'],
    isPartner: true,
  },
  {
    name: 'SSSAiCode',
    providerType: 'sssaicode',
    defaultModel: 'gpt-5.5',
    defaultBaseUrl: 'https://node-hk.sssaicodeapi.com/api/v1',
    websiteUrl: 'https://sssaicodeapi.com',
    apiKeyUrl: 'https://sssaicodeapi.com/register?ref=DCP0SM',
    apiFormat: 'openai_responses',
    icon: 'sssaicode',
    iconColor: '#000000',
    endpointCandidates: [
      'https://node-hk.sssaicodeapi.com/api/v1',
      'https://node-hk.sssaiapi.com/api/v1',
      'https://node-cf.sssaicodeapi.com/api/v1',
    ],
    category: 'third_party',
    isPartner: true,
  },
  {
    name: '优云智算',
    providerType: 'compshare',
    defaultModel: 'gpt-5.5',
    defaultBaseUrl: 'https://api.modelverse.cn/v1',
    websiteUrl: 'https://www.compshare.cn',
    apiKeyUrl: 'https://www.compshare.cn/coding-plan?ytag=GPU_YY_YX_git_cc-switch',
    apiFormat: 'openai_responses',
    icon: 'ucloud',
    iconColor: '#000000',
    endpointCandidates: ['https://api.modelverse.cn/v1'],
    category: 'aggregator',
    isPartner: true,
  },
  {
    name: '优云智算Coding Plan',
    providerType: 'compshare_coding_plan',
    defaultModel: 'gpt-5.5',
    defaultBaseUrl: 'https://cp.compshare.cn/v1',
    websiteUrl: 'https://www.compshare.cn',
    apiKeyUrl: 'https://www.compshare.cn/coding-plan?ytag=GPU_YY_YX_git_cc-switch',
    apiFormat: 'openai_responses',
    icon: 'ucloud',
    iconColor: '#000000',
    endpointCandidates: ['https://cp.compshare.cn/v1'],
    category: 'aggregator',
    isPartner: true,
  },
  {
    name: 'Micu',
    providerType: 'micu',
    defaultModel: 'gpt-5.5',
    defaultBaseUrl: 'https://www.micuapi.ai/v1',
    websiteUrl: 'https://www.micuapi.ai',
    apiKeyUrl: 'https://www.micuapi.ai/register?aff=aOYQ',
    apiFormat: 'openai_responses',
    icon: 'micu',
    iconColor: '#000000',
    endpointCandidates: ['https://www.micuapi.ai/v1'],
    category: 'third_party',
    isPartner: true,
  },
  {
    name: 'ETok.ai',
    providerType: 'etok_ai',
    defaultModel: 'gpt-5.5',
    defaultBaseUrl: 'https://api.etok.ai/v1',
    websiteUrl: 'https://etok.ai',
    apiKeyUrl: 'https://etok.ai',
    apiFormat: 'openai_responses',
    icon: 'etok',
    iconColor: '#000000',
    endpointCandidates: ['https://api.etok.ai/v1'],
    category: 'third_party',
    isPartner: true,
  },
  {
    name: 'E-FlowCode',
    providerType: 'e_flowcode',
    defaultModel: 'gpt-5.5',
    defaultBaseUrl: 'https://e-flowcode.cc/v1',
    websiteUrl: 'https://e-flowcode.cc',
    apiKeyUrl: 'https://e-flowcode.cc',
    apiFormat: 'openai_responses',
    icon: 'eflowcode',
    iconColor: '#000000',
    endpointCandidates: ['https://e-flowcode.cc/v1'],
    category: 'third_party',
  },
  {
    name: 'PIPELLM',
    providerType: 'pipellm',
    defaultModel: 'gpt-5.5',
    defaultBaseUrl: 'https://cc-api.pipellm.ai/v1',
    websiteUrl: 'https://code.pipellm.ai',
    apiKeyUrl: 'https://code.pipellm.ai/login?ref=uvw650za',
    apiFormat: 'openai_responses',
    icon: 'pipellm',
    endpointCandidates: ['https://cc-api.pipellm.ai/v1'],
    category: 'aggregator',
  },
  {
    name: 'OpenRouter',
    providerType: 'openrouter',
    defaultModel: 'gpt-5.5',
    defaultBaseUrl: 'https://openrouter.ai/api/v1',
    websiteUrl: 'https://openrouter.ai',
    apiKeyUrl: 'https://openrouter.ai/keys',
    apiFormat: 'openai_responses',
    icon: 'openrouter',
    iconColor: '#6566F1',
    category: 'aggregator',
  },
  {
    name: 'TheRouter',
    providerType: 'therouter',
    defaultModel: 'openai/gpt-5.3-codex',
    defaultBaseUrl: 'https://api.therouter.ai/v1',
    websiteUrl: 'https://therouter.ai',
    apiKeyUrl: 'https://dashboard.therouter.ai',
    apiFormat: 'openai_responses',
    endpointCandidates: ['https://api.therouter.ai/v1'],
    category: 'aggregator',
  },
]

export const MODEL_CONFIG_PRESETS = PRESETS

export function findModelConfigPreset(providerType?: string | null) {
  return MODEL_CONFIG_PRESETS.find((preset) => preset.providerType === providerType) ?? MODEL_CONFIG_PRESETS[0]
}
